[build]
builder = "nixpacks"

[[services]]
name = "backend"
[services.env]
PORT = "3000"

[[services]]
name = "evolution-api"
root = "services/evolution-api"
source = "Dockerfile"
[services.env]
SERVER_PORT = "8080"
