[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "npm start"
